// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsTa1X_LI8in4wrZWX_wEUsrU5RDvvbnw',
    appId: '1:732531625927:web:21445d5880363c4eb453e2',
    messagingSenderId: '732531625927',
    projectId: 'kasir-270cc',
    authDomain: 'kasir-270cc.firebaseapp.com',
    storageBucket: 'kasir-270cc.firebasestorage.app',
    measurementId: 'G-3B203GBWRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWC-d6u5fA2sewQOKZdLZqG2a2MNcVWoc',
    appId: '1:732531625927:android:81939e6ab0fea7dbb453e2',
    messagingSenderId: '732531625927',
    projectId: 'kasir-270cc',
    storageBucket: 'kasir-270cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJu8A8MhhTktUHJG3qjTfhSirn4ZCESdg',
    appId: '1:732531625927:ios:31a0dd9f009bb786b453e2',
    messagingSenderId: '732531625927',
    projectId: 'kasir-270cc',
    storageBucket: 'kasir-270cc.firebasestorage.app',
    iosBundleId: 'com.example.kasir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJu8A8MhhTktUHJG3qjTfhSirn4ZCESdg',
    appId: '1:732531625927:ios:31a0dd9f009bb786b453e2',
    messagingSenderId: '732531625927',
    projectId: 'kasir-270cc',
    storageBucket: 'kasir-270cc.firebasestorage.app',
    iosBundleId: 'com.example.kasir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsTa1X_LI8in4wrZWX_wEUsrU5RDvvbnw',
    appId: '1:732531625927:web:a7c7d31e0a4cd15cb453e2',
    messagingSenderId: '732531625927',
    projectId: 'kasir-270cc',
    authDomain: 'kasir-270cc.firebaseapp.com',
    storageBucket: 'kasir-270cc.firebasestorage.app',
    measurementId: 'G-GDKMDPV9QD',
  );

}